
print("Think of a number,")
input("Press enter:")
print(" now Double your number.")
input("Press Enter:")
print("now add 10 to it.")
input("Press Enter:")
print("NOW divide the result by 2.")
input("Press Enter:")
print("now subtract ir from original number.")
input("Press Enter:")
print("Your final number is 5")
